# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# The `chdir` argument of the `command` module unexpectedly fails in this case,
# so use the `shell` module and explicitly change into the correct directory.
# https://serverfault.com/questions/573843/ansible-playbook-not-working-trying-to-run-make-configure-with-complex-switche
- name: install npm modules
  npm: path="{{clone_path}}"

- name: build site with jekyll
  shell: cd {{clone_path}} && jekyll build --destination {{jekyll_output_path}}
  args:
    creates: "{{jekyll_output_path}}"

- name: generate build info file
  template: src=build_info.txt dest={{clone_path}}/{{build_info_path}}
  when: build_info_path is defined
